Glitchfiend/BiomesOPlenty

- src/main/java/biomesoplenty/common/core/BOPCrafting.java
In the changed code below, there is an unneeded if statement causing the Mahogany wood problem in issue #369.  I'm not sure about the flowerStem component of that issue, and I'm not attempting to address it here.
i == 3 is a Mohagony log.  Due to this bug it is currently not registered as logWood, and with this fix it is.
> Issue #369 add Mahogany logs as a logWood resource

- src/main/java/biomesoplenty/client/fog/FogHandler.java
- src/main/java/biomesoplenty/common/biome/nether/BiomeGenPolarChasm.java
- src/main/java/biomesoplenty/common/biome/overworld/BiomeGenBambooForest.java
- src/main/java/biomesoplenty/common/biome/overworld/BiomeGenOminousWoods.java
- src/main/java/biomesoplenty/common/biome/overworld/BiomeGenTropicalRainforest.java
This should make the fog usable in biomes now.  The 3 biomes with 0.01 fog densities have been switched to 0.99, since that seemed like the real intention.
> Scale fog density to far plane distance.

- src/main/java/biomesoplenty/client/fog/FogHandler.java
- src/main/java/biomesoplenty/common/configuration/BOPConfigurationMisc.java
This fixes an oversight I made when moving the near-plane distance closer to enhance dense fog biomes, causing haziness in biomes which shouldn't have closer fog.
This sets the near plane distance between 0.1 and 0.75 (vanilla) of the far plane distance based on the 0.0 - 1.0 fog density of the biome.
I also added two boolean config properties to toggle the fog color and density, since the restoration of this feature may not be welcome by all players or packs.
> Fix fog render and add configuration

- src/main/java/biomesoplenty/client/fog/FogHandler.java
Ensure a non-zero distance.  Zero-distances send all the color channels to +Infinity or -Infinity.
> Fix fog color calculation in 'fast' graphics mode.

- src/main/java/biomesoplenty/common/handlers/FurnaceFuelHandler.java
Passing a badly implemented itemstack (the stack for some reason returns null for getItem) is passed the game will crash with a NPE.
Here is an example crash report: http://pastebin.com/K0vpKQ6N
> Avoid NPE in the fuel handler

- src/main/java/biomesoplenty/common/blocks/BlockBOPNewGrass.java
Added limits to meta to prevent ArrayIndexOutOfBoundsException similar to BlockBOPNewDirt.java. 
Still probably a deeper issue here, but this will prevent crashes for now
> Fixed #442

- src/main/java/biomesoplenty/common/blocks/BlockBOPNewGrass.java
Removed renderAsNormalBlock returning false to allow beds, torches, and monsters to spawn. Tested that block still renders the grass correctly.
> Fixed #433

- src/main/java/biomesoplenty/common/blocks/BlockBOPSapling.java
- src/main/java/biomesoplenty/common/recipes/BiomeEssenceRecipe.java
Fixes #230 and also fixed missing apple and persimmon leaves. Why not to use them if they have textures and already implemented? Might be just an oversight. @Adubbz if you need to change something just say.
> Register biome essence recipe Fixes #230

- src/main/java/biomesoplenty/common/blocks/templates/BOPBlockWorldDecor.java
Added null check for itemstack to prevent crashing when getting metadata from null itemstack. In response of simeonradivoev/MatterOverdrive#150
> Added itemstack null check on canReplace

- src/main/java/biomesoplenty/common/world/ChunkProviderBOPHell.java
Relates to issue #257 . Upon entering the Nether, I noticed that lava source blocks in the roof were not flowing. This change appears to fix the problem.
> Fix for lava not flowing from ceiling on chunk creation in Nether

- src/main/java/biomesoplenty/common/core/BOPBiomes.java
See comments on Glitchfiend/BiomesOPlenty#602. The intent of this pull request is to keep BoP for 1.7.10 generating the same terrain with the same config.
I understand it may not be technically correct though, so feel free to disregard if it's no good.
> Make wetlands warm again (fix #602)

- src/main/java/biomesoplenty/common/blocks/BlockBOPPetals.java
Because it makes non-usable flowers in recipes..
> Return null dropped metadata from giant flowers

- build.properties
- src/main/java/biomesoplenty/common/init/ModItems.java
Forge have recently made some changes to EnumHelper, which breaks the way I told you to add the armor material when EnumHelper.addArmorMaterial was broken. It's fixed now though, so I just switched back to that.
> Fixed BoP crashing on newer version of Forge Closes #773

- src/main/java/biomesoplenty/common/blocks/BlockBOPNewFarmland.java
Server is Running FTB Infinity Evolved 2.5.0
About the Crash:
A player made a field of Loamy Dirt and used a Hoe on it (to get Farmland) - it was also near to water (wet).
Client Crashed with OOB.in getIcon @ BlockBOPNewFarmland.java:75
After comparing with BlockBOPNewGrass's getIcon i noticed there's no check on metadata > types length.
As i'm currently a bit short in time, i had no time to dig deeper into the code, but it seems to be valid from my perspective to just add the missing checks.
Link to crash-report:
http://pastebin.com/k2SmTdHK
> Crashfix for 'Wet' Loamy Farmland

- src/main/java/biomesoplenty/api/generation/GeneratorStage.java
Switches GeneratorStage decorate type mapping to an EnumMap to provide forwards-compatibility; fixes the spawning of trees (and other decorate things) on newer versions of Forge.
Tested to be working on latest Forge version.
Fixes #818
> Fix spawning of trees on newer versions of Forge

- src/main/java/biomesoplenty/common/item/ItemBOPScythe.java
See #816 for more information
The solution is to not let the trim logic touch the original targeted block, and let vanilla handle its breaking as normal.
> Skip original position when trimming, closes #816

- src/main/java/biomesoplenty/common/handler/AchievementEventHandler.java
There are two parts to the issue, a dupe and a crash. The dupe occurs when the handling for the `PlaceEvent` throws an exception, causing the stack in the player's inventory to not be decremented. Initial [stacktrace](https://paste.ee/p/IYNlj) (line 621). The crash occurs with Extra Utilities 2's Mechanical User, when set in `Use Item on Block` mode, attempting to place a piston. [log](https://paste.ee/p/l1Y3a)
This also fixes #950 
The issue was tracked down to [AchievementEventHandler.java#L184](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.10.2-5.0.x/src/main/java/biomesoplenty/common/handler/AchievementEventHandler.java#L184) and the use of `Block#getStateFromMeta()` (which has been deprecated). Rewriting the handler to use the `IBlockState` from …
> [1.10.2] Fixed piston dupe/crash

- src/main/java/biomesoplenty/common/init/ModCrafting.java
The exact same thing as #1002 
>I'm working on adding support for the Biomes o' Plenty gems in the MoreChickens mod. However, for that I would need amethyst to have an ore dictionary entry.
>
>I looked through old issues on the issue tracker here, the main concern seemed to be that it's an endgame item, and shouldn't be easier to get through other mods. That is why I did not modify the crafting recipes to use ore dictionary. So this will only allow other mods to use bop amethyst, but not the other way around.
> add amethyst to oreDict

- src/main/java/biomesoplenty/common/world/BiomeProviderBOPHell.java
This adds an override for `BiomeProvider#getBiomesForGeneration` to
`BiomeProviderBOPHell` that defaults to `Biomes.HELL` instead of
`Biomes.DEFAULT` (ocean) if a chunk's biome array contains -1.
> Override for #getBiomesForGeneration, fixes #1070

- src/main/java/biomesoplenty/common/fluids/blocks/BlockBloodFluid.java
- src/main/java/biomesoplenty/common/fluids/blocks/BlockHoneyFluid.java
- src/main/java/biomesoplenty/common/fluids/blocks/BlockHotSpringWaterFluid.java
- src/main/java/biomesoplenty/common/fluids/blocks/BlockPoisonFluid.java
- src/main/java/biomesoplenty/common/fluids/blocks/BlockQuicksandFluid.java
This initialises BoP fluids to have a hardness of 100.0F which matches
vanilla water and lava. Calling #setHardness subsequently sets the
blockResistance (blockHardness * 5.0F) which handles resistence to
explosions.
An exception was made for quicksand, which initializes to the same
hardness as minecraft:sand (0.5F) so that explosions won't leave piles
of quicksand floating around.
Closes #1186
> Initialize fluid hardness to match vanilla fluids

- src/main/java/biomesoplenty/common/block/BlockBOPBlueFire.java
- src/main/java/biomesoplenty/common/entities/projectiles/EntityMudball.java
- src/main/java/biomesoplenty/common/handler/TrailsEventHandler.java
- src/main/java/biomesoplenty/core/ClientProxy.java
- src/main/java/biomesoplenty/core/CommonProxy.java
This patch removes the World argument from the proxy method to spawn particles as it is not needed and will prevent consumers from using the server's world. We instead grab the World instance from `Minecraft#world` and return early if it's null (which is probably done in paranoia.)
> Use Minecraft#world when spawning particles on the client, fixes #1368

- src/main/java/biomesoplenty/api/enums/BOPFlowers.java
- src/main/java/biomesoplenty/api/enums/BOPGems.java
- src/main/java/biomesoplenty/api/enums/BOPPlants.java
- src/main/java/biomesoplenty/api/enums/BOPTrees.java
- src/main/java/biomesoplenty/api/enums/BOPWoods.java
- src/main/java/biomesoplenty/client/gui/GuiBOPFactory.java
- src/main/java/biomesoplenty/common/biome/BOPBiome.java
- src/main/java/biomesoplenty/common/biome/overworld/BiomeGenAlps.java
- src/main/java/biomesoplenty/common/biome/overworld/BiomeGenMountain.java
- src/main/java/biomesoplenty/common/biome/overworld/BiomeGenRedwoodForest.java
- src/main/java/biomesoplenty/common/biome/overworld/BiomeGenTundra.java
- src/main/java/biomesoplenty/common/block/BlockBOPCoral.java
- src/main/java/biomesoplenty/common/block/BlockBOPDirt.java
- src/main/java/biomesoplenty/common/block/BlockBOPDoubleDecoration.java
- src/main/java/biomesoplenty/common/block/BlockBOPDoublePlant.java
- src/main/java/biomesoplenty/common/block/BlockBOPGrass.java
- src/main/java/biomesoplenty/common/block/BlockBOPHalfOtherSlab.java
- src/main/java/biomesoplenty/common/block/BlockBOPHive.java
- src/main/java/biomesoplenty/common/block/BlockBOPLilypad.java
- src/main/java/biomesoplenty/common/block/BlockBOPMud.java
- src/main/java/biomesoplenty/common/block/BlockBOPMushroom.java
- src/main/java/biomesoplenty/common/block/BlockBOPSeaweed.java
- src/main/java/biomesoplenty/common/block/BlockBOPTerrarium.java
- src/main/java/biomesoplenty/common/block/BlockBOPWhiteSandstone.java
- src/main/java/biomesoplenty/common/item/ItemJarFilled.java
- src/main/java/biomesoplenty/common/world/BOPWorldSettings.java
- src/main/java/biomesoplenty/core/BiomesOPlenty.java
- src/main/java/biomesoplenty/core/ClientProxy.java
14ce249 changes the default locale, which affects many server mods or plugins. Server mods and plugins are not able to change the behavior of clients so the i18n works can only be done on server side, and many of them identify which language to use by `Locale.getDefault()`.
The default locale can be passed in via command args such as `-Duser.country=XX -Duser.language=xx` while it is hardcoded to `Locale.ENGLISH` in the latest release of BOP.
Maybe it is also necessary to cherry-pick these commits into 1.13+ branches in my opinion.
> Fix #760 without changing the default locale to en_us

- src/main/java/biomesoplenty/common/crafting/BiomeEssenceRecipe.java
Here's a video illustrating the problem (set it to HD and watch the panel in the background as I move the 2 types of biome essence into the crafting grid):
https://youtu.be/lR7Sxcuiny4
The correct response is "oops" :D
> Prevent modification of ItemStack.EMPTY's NBT

- src/main/java/biomesoplenty/common/world/layer/RainfallNoiseLayer.java
- src/main/java/biomesoplenty/common/world/layer/TemperatureNoiseLayer.java
This PR changes the climate offsetting to use Java Random's nextDouble to ensure that all climates will be generated in every seed.
Fixes #1648
> Change climate offsetting to random instead of bitmask

- src/main/java/biomesoplenty/common/world/SimplexNoise.java
- src/main/java/biomesoplenty/common/world/layer/RainfallNoiseLayer.java
- src/main/java/biomesoplenty/common/world/layer/TemperatureNoiseLayer.java
Improves contrast and gradient direction variation in the simplex noise used for temperature and rainfall pattern distributions. Also adds true seedable functionality, so the whole pattern changes per world instead of it shifting around. I updated the group bounds in the biome noise layers to match the new noise.
Current:
New:
Bonus: Now when you run the main method in SimplexNoise.java through the dev console, you get this:
Ingame screenshots. Taken on a world with multiple mods, but the biome layers are unchanged from BOP's
> Improve simplex noise code and results, make it fully seedable.
