Glitchfiend/BiomesOPlenty

src/main/resources/assets/biomesoplenty/lang/fr_CA.lang

Changing the Toadstool to make it edible instead of poisonous since it's used in a recipe

Updating French Canadian language

---

src/main/java/biomesoplenty/client/fog/FogHandler.java

This re-enables fog color and distance rendering.
The fog can be made much smoother by interpolating the edge squares based on the player's position within its current square.  Both fog color and fog distance are greatly smoothed out this way.
Should resolve the concerns in #251 .

Smooth fog color and distance rendering

---

src/main/java/biomesoplenty/client/fog/FogHandler.java

This PR does several things, and was prompted by a comment left in #432:
- Set a correct fog when submerged in water or lava.  As a bonus, the water fog will receive a biome-appropriate tint.  Check normal/sludge-pit boundary for most visual impact.  It's mostly subtle.
- Apply other post-processing that I missed.  Void fog, blindness, and night vision (de-)buffs.  An interesting fact about the combination of those two effects is embedded in a comment.
- Fix the mix order for biome fog.  Since the input default color has already been fully processed, performing any processing on the mixed result effectively double-applied for a portion of the result.
- Ditch all intermediate packed color representations.  The minor precision loss really exploded for certain transformations (in particular …

Fog: water, mix order, precision, post-processing

---

src/main/java/biomesoplenty/common/itemblocks/ItemBlockFruit.java

Subject Explains Everything.
Introduced in 4215cc8e3d6e24da2c9d7c8019ec063afce593b2
The Bug also caused NEI to crash the Client in several cases

Fixed Array-Bounds-Check 

---

src/main/java/biomesoplenty/common/blocks/BlockHive.java
src/main/java/biomesoplenty/common/items/ItemJarFilled.java

Do not spawn wasp or pixie entities that have config IDs set to 0. Also fixed minor bug where empty jar was not placed back into player hand after spawning pixie

Fixed #419

---

src/main/java/biomesoplenty/common/core/BOPBlocks.java

Enable leaves and logs to burn.

Fixed #392

---

src/main/java/biomesoplenty/common/blocks/BlockBOPColorizedSapling.java
src/main/java/biomesoplenty/common/blocks/BlockBOPSapling.java

Fixed bug where two saplings dropped on a neighbor block change.

Fixed #406 and #450

---

src/main/java/biomesoplenty/common/blocks/BlockBOPColorizedSapling.java
src/main/java/biomesoplenty/common/items/ItemJarFilled.java

Not sure if everything done is correctly but it compiles and world is loads. Closes #468 and #469

Fixed compile issues Closes #468 and #469

---

src/main/java/biomesoplenty/common/items/ItemBOPPickaxe.java

[Before](http://i.imgur.com/d2lBGKe.jpg)
[After](http://i.imgur.com/jkuEcdS.jpg)
Closes #358

Fix incorrect Harvest level for mud pick

---

src/main/java/biomesoplenty/common/core/BOPCrafting.java

Everything made to be inline with Harvestcraft Ore Dictionary. Closes #327 and #451

Additional OreDictionary support

---

src/main/java/biomesoplenty/common/world/features/trees/WorldGenMiniShrub.java

Prevents Hellbark Trees from breaking other blocks

Fixed #370

---

src/main/java/biomesoplenty/common/blocks/BlockBones.java
src/main/java/biomesoplenty/common/itemblocks/ItemBlockBones.java
src/main/java/biomesoplenty/common/itemblocks/ItemBlockGrave.java

Fixed bone segment placement bug

Fixes #390

---

src/main/java/biomesoplenty/common/itemblocks/ItemBlockBOPLilypad.java

Prevent crash in ItemBlockBOPLilypad.java

Fixes #453

---

src/main/java/biomesoplenty/common/crafting/BiomeEssenceRecipe.java

Same as #503 but for 1.8. Leaves should be fixed already.

Register biome essence recipe for 1.8

---

src/main/java/biomesoplenty/common/items/ItemBOPAxe.java

Build compiles successfully with these changes.

Fix axes Closes #514

---

src/main/java/biomesoplenty/common/core/BOPCrafting.java

Tested on Pure Daisy from Botania. Everything seems to working.

Fixed sideways logs weren't oredicted Closes #525

---

src/main/java/biomesoplenty/common/core/BOPCrafting.java

Switched to use ore dictionary entries in recipes, registered gem blocks in ore dictionary. @Adubbz what do you think if I register Ender Amethyst in ore dictionary? It's shouldn't hurt at all and most mods are registering their own (custom) metals/gems.

Use Ore Dictionary in recipes

---

src/main/java/biomesoplenty/common/core/BOPCrafting.java
src/main/java/biomesoplenty/common/core/BOPItems.java

From commits:
https://github.com/Glitchfiend/BiomesOPlenty/commit/12cf3f1a686bd70de26521fcc6c40b03cf64214a
https://github.com/Glitchfiend/BiomesOPlenty/commit/6fc07736da33f7e1b0bfbe40fab931c556ddf261

Backport balance tweaks to 1.7.10

---

src/main/java/biomesoplenty/common/blocks/BlockBOPAppleLeaves.java
src/main/java/biomesoplenty/common/blocks/BlockBOPColorizedLeaves.java
src/main/java/biomesoplenty/common/blocks/BlockBOPLeaves.java
src/main/java/biomesoplenty/common/blocks/BlockBOPPersimmonLeaves.java
src/main/java/biomesoplenty/common/blocks/templates/BOPBlockWorldDecor.java

re-pull of #586
@Adubbz should be good now? BetterFoliage is BetterGrassAndLeavesMod replacement for 1.7.10.
close #515
close #558

Fixed rare crash, BetterFoliage support

---

src/main/java/biomesoplenty/common/integration/BOPIntegration.java

Should fix issue discovered in #585
P.S I can't reproduce this issue using BoP 1609 and ForgeMultipart 1.2.0.345. So, not sure if it fixes it.

Move FMP integration to init

---

src/main/java/biomesoplenty/core/BiomesOPlenty.java

Sets the Default Locale to English. Fixes Issue #760

Fix for Issue #760 - Turkish Locale Bug

---

src/main/java/biomesoplenty/core/BiomesOPlenty.java

One of our server's users encountered the same problem once again with dotless i, as I never pushed to the most recent branch, here is the fix once again!

Fix for Turkish Locale bug in 1.10+

---

src/main/java/biomesoplenty/common/entities/ai/EntityAIEatBOPGrass.java
src/main/java/biomesoplenty/common/handler/SheepEventHandler.java

- Sheep now also eat BoP variants for tall grass

Fixed that sheep won't eat BoP grass Fixes #823

---

src/main/java/biomesoplenty/common/init/ModItems.java

Btw, Forge has an ItemAxe constructor that allows you to set the speed and damage. I figured I would go ahead and fix this for now, though.

Fixed setting axe speed

---

src/main/java/biomesoplenty/common/handler/UseHoeEventHandler.java

Fixed sound when hoeing BoP farmland as well

Changed the way hoes get damaged when hoeing BoP Farmland for better mod support

---

src/main/java/biomesoplenty/common/handler/ItemEventHandler.java
src/main/java/biomesoplenty/common/inventory/ContainerFlowerBasket.java
src/main/java/biomesoplenty/common/inventory/InventoryFlowerBasket.java
src/main/java/biomesoplenty/common/item/ItemFlowerBasket.java
src/main/java/biomesoplenty/common/util/entity/PlayerUtil.java

* Fixed that the flower basket didn't remove the flower from the player inventory on pickup.
* Fixed a couple of crashes with the flower basket as well.

Fixed Flower Basket

---

src/main/java/biomesoplenty/common/handler/AchievementEventHandler.java

Re-implemented some achievements that have been commented out for a while
Slight cleanup of AchievementEventHandler

Fixed some achievements not working

---

src/main/java/biomesoplenty/common/init/ModCrafting.java

Made recipes using mud use the oredict entry "ballMud"
Minor cleanup in ModCrafting
New recipes can be seen here: http://imgur.com/a/0e6Lp

Added some vanilla convenience recipes, closes #632

---

src/main/java/biomesoplenty/client/gui/GuiBOPConfigureWorld.java
src/main/java/biomesoplenty/common/world/BOPWorldSettings.java
src/main/java/biomesoplenty/common/world/ChunkProviderGenerateBOP.java

Specifically:
- Main Noise X/Y/Z
- Coordinate Scale
- Height Scale
- Lower/Upper Limit Scale
See also #929

Make some noise params from vanilla configurable

---

src/main/java/biomesoplenty/client/gui/GuiBOPConfigureWorld.java
src/main/java/biomesoplenty/common/world/BOPWorldSettings.java
src/main/java/biomesoplenty/common/world/ChunkProviderGenerateBOP.java

Specifically:
- Main Noise X/Y/Z
- Coordinate Scale
- Height Scale
- Lower/Upper Limit Scale
Will make another PR against the 1.11.x branch. Let me know if there's anything you'd like done differently!

Make some noise params from vanilla configurable (1.10.2)

---

build.properties
src/main/java/biomesoplenty/common/handler/AchievementEventHandler.java

Updated to latest RB of Forge.

Fixes crash when picking up pistons

---

build.properties
src/main/java/biomesoplenty/client/gui/GuiBOPConfigureWorld.java
src/main/java/biomesoplenty/client/gui/GuiBOPPageTable.java
src/main/java/biomesoplenty/client/gui/inventory/GuiFlowerBasket.java

- Update Forge to 13.20.0.2224: no changes
- update MCP mappings to snapshot_nodoc_20170121: 1 change
- `field_146289_q`, `fontRendererObj` -> `fontRenderer`

Update to 1.11.2

---

src/main/java/biomesoplenty/common/util/entity/PlayerUtil.java

* re https://github.com/SleepyTrousers/EnderIO/issues/4218

Prevent crashes when the used item cannot be found on the player

---

src/main/java/biomesoplenty/common/util/block/BlockQuery.java

Use canSustainPlant to check for fertility instead of own implementation

---

src/main/java/biomesoplenty/common/item/ItemBiomeFinder.java

Additional null check, to hopefully prevent issues in the future
Some minor cleanup

Fixed biome finder not working on servers, Closes #1109

---

src/main/java/biomesoplenty/common/item/ItemFlowerBasket.java

Fixed a few possible NPEs
Could not find any way to fix the anvil naming issue though.

Improved Flower Basket support, Closes #999

---

src/main/java/biomesoplenty/common/blocks/BlockBOPColorizedSapling.java

Should prevent mangrove saplings from randomly popping off of sand.

Added bitmask before checking block below sapling

---

src/main/java/biomesoplenty/common/block/BlockBOPBlueFire.java
src/main/java/biomesoplenty/common/block/BlockBOPDoor.java
src/main/resources/assets/biomesoplenty/lang/en_US.lang
src/main/resources/assets/biomesoplenty/models/item/blue_fire.json

- Fixed Blue Fire inventory render, to prevent errors on startup
- Fixed Earth item not having localization
- Fixed client SideOnlys on a few getPickBlock methods

Various misc fixes

---

src/main/java/biomesoplenty/common/entities/item/EntityBOPBoat.java

Fixed BoP boat creative pick result

Fixed BoP boats not being breakable by hand, Fixed #1197

---

src/main/java/biomesoplenty/common/command/BOPCommand.java

I use BoPs tpbiome command all the time when modding, nad it have always bugged me I had to manually input the biome name. Finally got around to make a PR to fix it ^^

Added auto completion for tpbiome command

---

src/main/java/biomesoplenty/api/entity/BOPEntities.java
src/main/java/biomesoplenty/common/entity/item/BoatEntityBOP.java
src/main/resources/META-INF/accesstransformer.cfg

and also removes the import in the api

fix boat inputs allowing to move

---

src/main/resources/assets/biomesoplenty/advancements/biomesoplenty/all_biomes.json

As with my other PR, I don't know if this affects the other branches as well, so I'd suggest you check those out as well.

Fix duplicate JSON key in all_biomes.json

---

src/main/java/biomesoplenty/init/ModFeatures.java

Added a single class that registers all of BoP's features to allow it to be more mod friendly so other mods can find and access BoP's features now for whatever reason. I tried to keep the class in the style of other BoP's registering classes as well. 
I hope this helps!

Register all BoP features now into Forge's feature Registry

---

src/main/java/biomesoplenty/common/world/gen/feature/tree/BushTreeFeature.java

Oh man you screwed up the specificity of `&&` and `||`

fix infinite loop in BushTreeFeature

---

src/main/java/biomesoplenty/common/world/AlphaOctavePerlinNoise.java
src/main/java/biomesoplenty/common/world/AlphaPerlinNoise.java
src/main/java/biomesoplenty/common/world/gen/feature/BOPConfiguredFeatures.java
src/main/java/biomesoplenty/common/world/gen/placement/AlphaTreePlacement.java
src/main/java/biomesoplenty/common/world/gen/placement/BOPPlacements.java
src/main/java/biomesoplenty/common/world/gen/surfacebuilders/OriginHillsSurfaceBuilder.java
src/main/resources/META-INF/accesstransformer.cfg

This pull request improves the Origin Hills biome by implementing Alpha's tree generation noise and changing beach generation to use Alpha's sand generation and gravel generation algorithms.
Here are some screenshots showcasing the changes:

Improve Origin Hills tree generation and beach generation
